[build]
  publish = "./dist/"
  command = "export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && (npm install --no-optional && npx --no-install elm-tooling install) && npm install --no-optional && npm run build"

[build.environment]
  ELM_HOME = "$NETLIFY_BUILD_BASE/cache/elm"
  NO_ELM_TOOLING_INSTALL = "1"
  VERSION = "production"